// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sync.API.Persistance;

namespace Sync.API.Persistance.Migrations
{
    [DbContext(typeof(SyncContext))]
    partial class SyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sync.API.Persistance.Models.Articulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("OrdenId");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImpuestos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity);

                    b.HasIndex("OrdenId");

                    b.ToTable("Articulos","dbo");
                });

            modelBuilder.Entity("Sync.API.Persistance.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("OrdenId");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity);

                    b.HasIndex("OrdenId");

                    b.ToTable("Cliente","dbo");
                });

            modelBuilder.Entity("Sync.API.Persistance.Models.ColaArticulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaActualizacion");

                    b.Property<DateTime>("FechaRegistro");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("Sincronizado");

                    b.HasKey("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity);

                    b.ToTable("ColaArticulos","dbo");
                });

            modelBuilder.Entity("Sync.API.Persistance.Models.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaOrden");

                    b.Property<long>("NumeroOrden");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImpuestos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrdenId")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity);

                    b.ToTable("Orden","dbo");
                });

            modelBuilder.Entity("Sync.API.Persistance.Models.Articulos", b =>
                {
                    b.HasOne("Sync.API.Persistance.Models.Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .HasConstraintName("FK_Articulos_Orden")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sync.API.Persistance.Models.Cliente", b =>
                {
                    b.HasOne("Sync.API.Persistance.Models.Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .HasConstraintName("FK_Cliente_Orden")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
